FROM python:3.10.13

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip
RUN pip3 install "numpy<2"
RUN pip3 install torch==2.3.1 torchvision==0.18.1 --index-url https://download.pytorch.org/whl/cpu

# install libs and frameworks
RUN pip3 install setuptools ;\
    pip3 install opencv-python ;\
    pip3 install patched_yolo_infer ;\
    pip3 install scikit-learn ;\
    pip3 install jupyterlab

WORKDIR /playground

# run the command
CMD ["jupyter", "lab", "--port=8789", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
